using System;
using System.Threading.Tasks;
using dotenv.net;
namespace UVACanvasAccess {
    internal static class Test {
        private const ulong TestUser1 = 3390,
                            TestUser2Id = 3392,
                            TestCourse = 1028,
                            TestDiscussion1 = 375,
                            TestDiscussion2 = 384;

        public static async Task Main(string[] args) {
            DotEnv.Config();
            
            var api = new Api(Environment.GetEnvironmentVariable("TEST_TOKEN"), 
                              "https://uview.instructure.com/api/v1/");

            var newTopic = await api.BuildNewCourseDiscussionTopic(TestCourse)
                                    .WithTitle("Programmatically Generated Topic")
                                    .WithMessage("Generated by UVACanvasAccess.")
                                    .AsPinned()
                                    .Post();

            Console.WriteLine(newTopic.ToPrettyString());
        }
    }
}