using System;
using System.IO;
using System.Threading.Tasks;
using dotenv.net;

namespace UVACanvasAccess {
    internal static class Test {
        private const ulong TestUser1 = 3390,
                            TestUser2Id = 3392,
                            TestCourse = 1028,
                            TestDiscussion = 375;

        public static async Task Main(string[] args) {
            DotEnv.Config();
            
            var api = new Api(Environment.GetEnvironmentVariable("TEST_TOKEN"), 
                              "https://uview.instructure.com/api/v1/");

            var filePath = Environment.GetEnvironmentVariable("TEST_FILE") ?? throw new Exception();
            var file = File.ReadAllBytes(filePath);

            var x = await api.PostCourseDiscussionEntry(TestCourse,
                                                        TestDiscussion,
                                                        "Programmatically generated by UVACanvasAccess.",
                                                        file,
                                                        filePath);

            Console.WriteLine(x);
        }
    }
}