using System;
using System.Threading.Tasks;
using dotenv.net;

namespace UVACanvasAccess {
    internal static class Test {
        private const ulong Test1Id = 3390;

        public static async Task Main(string[] args) {
            DotEnv.Config();
            
            var api = new Api(Environment.GetEnvironmentVariable("TEST_TOKEN"), 
                              "https://uview.instructure.com/api/v1/");

            var newUser = await api.BuildNewUser()
                                   .WithUniqueId("CANVAS_ACCESS_TEST_2")
                                   .WithName("UVACanvasAccess Test Account 2")
                                   .WithSkipRegistration()
                                   .WithTermsOfUseAccepted()
                                   .Post();

            newUser.Bio = "I am a test user programatically generated by UVACanvasAccess!";

            Console.WriteLine(newUser);
        }
    }
}