name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build-package:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Packages
      run: nuget restore UVACanvasAccess.sln
    - name: Compile Package
      working-directory: UVACanvasAccess
      run: nuget pack UVACanvasAccess.csproj -Build -Properties Configuration=Release -Properties BuildVersion=$(date "+%s")
    - uses: actions/upload-artifact@v4
      with:
        name: uvaca
        path: UVACanvasAccess/UVACanvasAccess*.nupkg
  build-docs:
 
   runs-on: ubuntu-latest
   
   steps:
   - name: Install doxygen
     run: sudo apt-get install -y doxygen graphviz
   - name: Checkout
     uses: actions/checkout@v2
   - name: Run doxygen
     run: doxygen UVACanvasAccess/Doxyfile
   - name: Deploy docs
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{secrets.GITHUB_TOKEN}}
       publish_dir: docs/html

  deploy-package:
  
    runs-on: ubuntu-latest
    needs: build-package
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: uvaca
    - name: Run deploy script
      run: curl -vX PUT -u "uvadev:${{secrets.GITHUB_TOKEN}}" -F package="@$(echo UVACanvasAccess.*.nupkg)" https://nuget.pkg.github.com/uvadev/
      shell: bash
